name: Build and Publish Snap

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: canonical/action-build@v1
        id: build-snap
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: snap
          path: ${{ steps.build-snap.outputs.snap }}
      - run: |
          sudo snap install --dangerous ${{ steps.build-snap.outputs.snap }}
          sudo snap connect add-private-ppa:password-manager-service
          add-private-ppa --help
      - name: Publish snap
        uses: canonical/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPSTORE_LOGIN}}

        if: ${{ env.SNAPCRAFT_STORE_CREDENTIALS != '' }}
        with:
          snap: ${{ steps.build-snap.outputs.snap }}
          release: edge
